export enum GelatoTaskRelay {
  NONE = 'NONE',
  ADD_FILE_WITH_PERMISSION = 'ADD_FILE_WITH_PERMISSION',
  REQUEST_CONTRIBUTION_PROOF = 'REQUEST_CONTRIBUTION_PROOF',
  REQUEST_REWARD = 'REQUEST_REWARD'
}